"""Adding the the sample data

Revision ID: 3f9033ff1d8f
Revises: 79efe5d95dbf
Create Date: 2025-03-06 12:47:24.330671

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f9033ff1d8f'
down_revision = '79efe5d95dbf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
